### ISSUE TITLE
Tags aren't avaliable on dockerhub

### ISSUE THREAD

**Issue by allenwu1973** [pgroonga/docker#5] opened 2020-10-16 08:28 UTC
Many tags listed in README aren't avaliable at dockerhub.

Specifically:
* 2.2.6-alpine-12-slim
* 2.2.6-alpine-11-slim
* 2.2.6-alpine-10-slim
* 2.2.6-alpine-12
* 2.2.6-alpine-11
* 2.2.6-alpine-10

Thanks

**Comment by ZenLiuCN** [comment] 2020-10-17 16:10
checked, there maybe some wrong with docker hub. I may check it , if I could got login in.

**Comment by ZenLiuCN** [comment] 2020-10-17 17:08
I have trigger a OneShot build for those tags. maybe check after some time. docker hub's building process is realy slow.

**Comment by ZenLiuCN** [comment] 2020-10-18 04:02
@allenwu1973 those tags should be avaliable, I'll close this issue.

**Closed by ZenLiuCN** 2020-10-18 04:02 UTC

**Comment by kou** [comment] 2020-10-19 00:48
This is caused by this https://github.com/docker/hub-feedback/issues/1831 Docker Hub problem.

**Comment by ZenLiuCN** [comment] 2020-10-19 11:44
I checked the build timeline old buid proceess failed while first time the tag created,I'm not sure about dose a tag source will be rebuilded. so just used a manual task.
